# Generated by Django 5.1.2 on 2024-11-02 15:10
from django.db import migrations, models
from ..models import Block

class Migration(migrations.Migration):
    dependencies = [
        ("experimento", "0001_initial"),  # Adjust this if the dependency is different
    ]

    operations = [
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block", models.ForeignKey("experimento.Block", on_delete=models.CASCADE)),  # String reference
                ("trial_id", models.IntegerField()),
                ("stimulus", models.CharField(max_length=10)),
                ("response", models.CharField(max_length=10, null=True, blank=True)),
                ("correct", models.BooleanField(null=True, blank=True)),
                ("reaction_time", models.FloatField(null=True, blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]