# Generated by Django 5.1.2 on 2024-11-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experimento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trial_id", models.IntegerField()),
                ("response", models.CharField(max_length=10)),
                ("reaction_time", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
