# Generated by Django 5.1.2 on 2024-11-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0002_experimentresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
